POST http://localhost:8080/api/v1/accounts
Content-Type: application/json

{
  "holderName": "Leonid",
  "accountType": "DEPOSIT",
  "openingBalance": 1000
}
###

POST http://localhost:8080/api/v1/accounts/ee2e7371-f2a9-4570-a4a9-a6c45a1d5ced/deposit
Content-Type: application/json

{
  "amount": 100
}
###

POST http://localhost:8080/api/v1/accounts/1550625c-d662-4c8a-aff0-7f345ee5d4fb/withdraw
Content-Type: application/json

{
  "amount": 200
}
###

DELETE http://localhost:8080/api/v1/accounts/ee2e7371-f2a9-4570-a4a9-a6c45a1d5ced
###

POST http://localhost:8080/api/events/accounts/replay
###

GET http://localhost:8082/api/v1/accounts/ee2e7371-f2a9-4570-a4a9-a6c45a1d5ced